### ISSUE TITLE
Pdf not generation

### ISSUE THREAD

**Issue by antoniorrm** [vspedr/react-pdfmake-example#1]

**Comment by vspedr** [comment]
Hi @antoniorrm, can you please provide more details?

**Comment by antoniorrm** [comment]
I downloaded the installation but I did not generate the pdf, I click to generate but it opens another page but nothing happens

**Comment by vspedr** [comment]
@antoniorrm what browser and OS are you using? I tested with chrome and firefox on linux and both are working

**Comment by antoniorrm** [comment]
I use Sierra in mac os, and tested with chrome
Atenciosamente,

*Antonio Raimundo Rocha Mendonça*
Estudante de Engenharia de Software UFC/ Campus Quixadá
Técnico em Redes de Computadores



Em ter, 30 de abr de 2019 às 08:52, Victor <notifications@github.com>
escreveu:

**Comment by vspedr** [comment]
Unfortunately I don't have a Mac so I'm not able to reproduce your problem, but it may be an issue with the  pdfmake library. This repo is only an example of how to integrate pdfmake in react apps, you could try cloning this repo and updating the library to see if it fixes the problem.

**Comment by antoniorrm** [comment]
Okay, thank you very much for your attention.
